[2024-08-12 22:18:17,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:18:17,431] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:18:17,431] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:18:17,431] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-12 22:18:17,431] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:18:17,440] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): also_run_this> on 2024-08-12 00:00:00+00:00
[2024-08-12 22:18:17,442] {standard_task_runner.py:52} INFO - Started process 35763 to run task
[2024-08-12 22:18:17,445] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', '/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpymjlq7vl', '--error-file', '/tmp/tmps61o8s8h']
[2024-08-12 22:18:17,445] {standard_task_runner.py:80} INFO - Job 18: Subtask also_run_this
[2024-08-12 22:18:17,478] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.also_run_this scheduled__2024-08-12T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-12 22:18:17,532] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2024-08-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-12T00:00:00+00:00
[2024-08-12 22:18:17,533] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-08-12 22:18:17,534] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=scheduled__2024-08-12T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2024-08-12 00:00:00+00:00: scheduled__2024-08-12T00:00:00+00:00, externally triggered: False>"']
[2024-08-12 22:18:17,539] {subprocess.py:85} INFO - Output:
[2024-08-12 22:18:17,540] {subprocess.py:92} INFO - run_id=scheduled__2024-08-12T00:00:00+00:00 | dag_run=<DagRun example_bash_operator @ 2024-08-12 00:00:00+00:00: scheduled__2024-08-12T00:00:00+00:00, externally triggered: False>
[2024-08-12 22:18:17,540] {subprocess.py:96} INFO - Command exited with return code 0
[2024-08-12 22:18:17,553] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20240812T000000, start_date=20240813T011817, end_date=20240813T011817
[2024-08-12 22:18:17,580] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-12 22:18:17,593] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
