[2024-08-12 22:18:20,381] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:18:20,387] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:18:20,387] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:18:20,388] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-12 22:18:20,388] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:18:20,403] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): run_after_loop> on 2024-08-12 00:00:00+00:00
[2024-08-12 22:18:20,405] {standard_task_runner.py:52} INFO - Started process 35794 to run task
[2024-08-12 22:18:20,407] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'example_bash_operator', 'run_after_loop', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', '/home/kai/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpiky1nc8u', '--error-file', '/tmp/tmppy2mmdjr']
[2024-08-12 22:18:20,408] {standard_task_runner.py:80} INFO - Job 20: Subtask run_after_loop
[2024-08-12 22:18:20,452] {task_command.py:370} INFO - Running <TaskInstance: example_bash_operator.run_after_loop scheduled__2024-08-12T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-12 22:18:20,507] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=run_after_loop
AIRFLOW_CTX_EXECUTION_DATE=2024-08-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-12T00:00:00+00:00
[2024-08-12 22:18:20,508] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-08-12 22:18:20,509] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo 1']
[2024-08-12 22:18:20,514] {subprocess.py:85} INFO - Output:
[2024-08-12 22:18:20,515] {subprocess.py:92} INFO - 1
[2024-08-12 22:18:20,515] {subprocess.py:96} INFO - Command exited with return code 0
[2024-08-12 22:18:20,537] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20240812T000000, start_date=20240813T011820, end_date=20240813T011820
[2024-08-12 22:18:20,582] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-12 22:18:20,612] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
